version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: mongodb://mongo:27017/ssys_employees
      JWT_SECRET: 4ec92806250a6a4119865c57b49a0aca80cdb043296cb9a3f6beaac41fe06d67 
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017