POST http://localhost:8000/employees
Content-Type: application/json

{
"name": "Anakin Skywalker",
"email": "skywalker@ssys.com.br",
"department": "Architecture",
"salary": "4000.00",
"birth_date": "01-01-1983"}



###

GET http://localhost:8000/employees

###

DELETE http://localhost:8000/employees/6534502a1c6506e208630234

###

GET http://localhost:8000/reports/employees/salary

###

POST http://localhost:8000/login
Content-Type:  application/json

{"username":"admin", "password":"password"}

###

POST http://localhost:8000/logout